#!/usr/bin/env python3
# Reference: ktpss95112, 2021 NTU CSIE NASA TA

import socket
import random
import hashlib
import time
from tqdm import tqdm
import os

HOST = f'linux{random.randint(7, 9)}.csie.ntu.edu.tw'
PORT = 6001

def interactive(s):
    while True:
        try:
            buf = input()
        except KeyboardInterrupt:
            break
        try:
            sendLine(s, buf)
            if buf=='1':
                data=""
                with open("solve/input", "r") as f:
                    data=f.read()
                sendLine(s, data)
            if buf=='2':
                data = "狗勾"*450
                leter=f"Dear Chiffon, {data}. Best wishes, name"
                sendLine(s, data)
            if buf=='3':
                for i in range(10):
                    POW(s)
            print(recvAll(s).decode(), end='')
        except BrokenPipeError:
            break


def recvUntil(s, suffix):
    suffix = suffix.encode() if isinstance(suffix, str) else suffix
    ret = b''
    while True:
        c = s.recv(1)
        ret += c
        if ret.endswith(suffix):
            break
    return ret


def recvLine(s):
    return recvUntil(s, '\n')


def recvAll(s):
    return s.recv(100000)


def sendLine(s, buf):
    buf = buf.encode() if isinstance(buf, str) else buf
    return s.sendall(buf + b'\n')


def POW(s):
    line = recvUntil(s, ' : ').decode()
    q = line[38:46]
    get = os.popen(f'grep {q} < {q[0]}/{q[1]}/{q[2:6]}')
    i = get.readline()[9:]
    #print(i[0:-1])
    sendLine(s, i[0:-1])


if __name__ == '__main__':
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.connect((HOST, PORT))
        POW(s)
        print(recvUntil(s, ': ').decode(), end='')
        interactive(s)
